export const RECEIVE_ADDRESS = 'receive_address' // 接收固定地址信息
export const RECEIVE_CURRENT_ADDRESS = 'receive_current_address' // 接收当前地址信息
export const RECEIVE_CATEGORYS = 'receive_categorys' // 接收分类数组
export const RECEIVE_SHOPS = 'receive_shops' // 接收商家数组
export const RECEIVE_USER_INFO = 'receive_user_info' //接收用户信息
export const RESET_USER_INFO = 'reset_user_info' //重置用户信息
export const RECEIVE_GOODS = 'receive_goods' //接收商品数组
export const RECEIVE_RATINGS = 'receive_ratings' //接收商品评论
export const RECEIVE_INFO = 'receive_info' //接收商家信息
export const INCREMENT_FOOD_COUNT = 'increment_food_count'
export const DECREMENT_FOOD_COUNT = 'decrement_food_count'
export const CLEAR_CART = 'clear_cart'
export const RECEIVE_SEARCH_SHOPS = 'receive_search_shops' //搜索
